name: camera_with_rtmp_phiz
description: Controlling the camera on Android and iOS plus rtmp live streaming support. Based off the Camera plugin.
version: 3.0.1
homepage: https://github.com/simpleman1984/camera_with_rtmp

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  path_provider: ^2.0.1
  video_player: ^2.4.0
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  pedantic: ^1.11.0
  mockito: ^5.0.7

dependency_overrides:
  crypto: ^3.0.2
  convert: ^3.0.1

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.whelksoft.camera_with_rtmp
        pluginClass: RtmppublisherPlugin
      ios:
        pluginClass: RtmppublisherPlugin
